server:
  port: 9000
kafka:
  bootstrapServers: localhost:9092
  groupID: kafka-sandbox
  topicName: myTopic
  autoOffsetReset: earliest

#okta:
#  oauth2:
#    issuer: https://{yourOktaDomain}/oauth2/default
#    client-id: {yourClientID}
#    client-secret: {yourClientSecret}