kafka:
  bootstrapServers: localhost:9092
  groupID: kafka-sandbox
okta:
  oauth2:
    issuer: https://{yourOktaDomain}/oauth2/default
    client-id: {yourClientID}
    client-secret: {yourClientSecret}
